[package]
name = "Sefsfuseenclave"
version = "1.0.0"
authors = ["Antfin"]
edition = "2018"

[lib]
name = "sefsfuseenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
log = "0.4"
#sgx_types = "=1.1.0"
#sgx_tstd = "=1.1.0"
