[package]
name = "rcore-fs-ext2"
version = "0.1.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"

[dependencies]
ext2 = { git = "https://github.com/rcore-os/ext2-rs" }
rcore-fs = { path = "../rcore-fs" }
